baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Arctic Blue Studio'
theme = 'ABS'
# enable images folder for assets
[[module.mounts]]
source = 'static'
target = 'static'
[[module.mounts]]
source = 'images'
target = 'static/images'
# Github Pages support
[caches]
  [caches.images]
	dir = ':cacheDir/images'